### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by FrankyMartz** [lucasmotta/sass-module-importer#3]
Plugin Fails for me. The following results in empty file.
### Gulp Task

``` javascript
var gulp = require("gulp");
var gSass = require("gulp-sass");
var gNotify = require("gulp-notify");
var moduleImporter = require("sass-module-importer");

gulp.task("sass", function(){
  return gulp.src(["main.scss"])
    .pipe(gSass({
      importer: [
        moduleImporter()
      ]
    }))
    .on("error", gNotify.onError())
      title: "SASS Compile Error",
      message: "<%= error.message %>"
    }))
    .pipe(gulp.dest(CONFIG.dist.styles));
});
```
### main.scss

``` sass
@import "normalize-scss";
```
### NPM Package

Testing with: [Normalize](https://github.com/JohnAlbin/normalize-scss)

**Comment by hjoseph96** [comment]
Same with colors.css for me

**Comment by dnutels** [comment]
Same with https://www.npmjs.com/package/sass-module-importer

**Comment by LeoAref** [comment]
Not working here also:

```
var gulp = require('gulp'),
    sass = require('gulp-sass'),
    moduleImporter = require('sass-module-importer'),

gulp.task('styles', function () {
    return gulp.src('./searchBox.scss')
        .pipe(sass({
            importer: moduleImporter()
        }))
        .on('error', sass.logError)
        .pipe(gulp.dest('./'));
```

**Comment by devnix** [comment]
Cannot import bootstrap and bourbon, too. Using Laravel Elixir

``` javascript
elixir(function(mix) {
    mix.sass('app.scss', null, { importer: moduleImporter() });
    mix.livereload(null, {
        port: 35729
    });
});
```

**Comment by yishus** [comment]
Same, not working

**Comment by lucasmotta** [comment]
Hey guys,

I've mentioned on #2 that the original implementation of this plugin was very naive.
I just released a new version (`1.2.0`) and tested with the following modules:

``` scss
@import "bulma";
@import "colors.css";
@import "normalize-scss";
@import "sass-spacing";
@import "font-awesome";
// or even require files inside that module, like bellow:
@import "font-awesome/scss/font-awesome.scss";

// mixin from normalize-scss
@include normalize();

.tile {
  // mixins from sass-spacing
  @include p(1);
  @include mt(2);
}
```

And this time, no problems. The dependencies are being properly resolved on a more robust way.
It will even inline `css` files, since Sass cannot do that (e.g. font-awesome is css).

I'm very confident that this will resolve most of the issues you guys were having. I will close it for now, but let me know if it comes back.

**Comment by CameronCarranza** [comment]
I'm still running into somewhat of a conflict with the "colors" dependency in NPM colliding with a `_colors.scss` import ( as import "colors" ). 

I was able to resolve my issue by namespacing the file as `_mysite_colors.scss` and now everything compiles perfectly. 

Only running into this since upgrading to NPM 3 with the flat file structure.

## EDIT

Appears to be happening with any like-named SCSS files regardless of directory location.

For example, if I have two separate `_hero.scss` files in two separate folders (`./pages/one/_one.scss referencing`hero`OR`./hero`in the same folder, and`./pages/two/_two.scss referencing `hero` OR `./hero` in its own folder), the highest one up is the only one that gets imported (also happened when imported as `./_hero.scss`).

When I check the compiled CSS the output will contain the contents of the first instance of that file, but no others. Not sure if anyone else is running into this, ~~I'm not fully updated on gulp-sass yet though I might try that next~~ Tried it with 2.2.0 and still occurring.

Looking forward to getting this working, especially with that CSS import implementation, something SASS has been missing.

**Comment by lucasmotta** [comment]
Hey @Radau - I'm working on it at the moment.

But there are two different issues from what I can see.

---

One of them is to distinguish between a local file vs a module. But that's not really a issue, you should use `./` on the local file, otherwise it would be impossible to know which one to import:

``` scss
@import 'colors'; /* returns the "colors" module */
@import './colors'; /* returns the local "colors" file */
```

---

The other one is the one I'm working on. At the moment, every single import goes through this library and is resolved.
So in the next release, this library will only handle external modules and it will ignore the local ones. So it means it shouldn't conflict or cache local files anymore.
